import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {AntdRegistry} from "@ant-design/nextjs-registry";
import Navbar from "@/app/components/Navbar";
import {Layout} from 'antd'
import Sidebar from "@/app/components/Sidebar";
import {getServerSession} from "next-auth";
import {authOptions} from "@/app/api/auth/[...nextauth]/route";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(
  {children}: Readonly<{ children: React.ReactNode; }>) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
    <body style={{height: "100vh"}} className={inter.className}>
    <AntdRegistry>
      <Layout>
        <Navbar userName={session?.user?.name}/>
        <Sidebar/>
        {/*  {children}*/}
      </Layout>
    </AntdRegistry>
    </body>
    </html>
  );
}
